---
AWSTemplateFormatVersion: 2010-09-09
Description: > 
    This is the network cfn template
    This is a practical lab on Udacity's nanodegree program.
    Trying to acheive the challenge on my own.

Parameters: 
  MyAZ: 
    Description: Availability zone
    Type: String
    Default: us-east-1a
Resources: 
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: MyVPCUdacityNDLap
  PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref MyAZ
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: PubSubnetA
  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGWUdacityLab
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyIGW
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebServerSG
      GroupDescription: this the sg that allows inbound traffic
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Web Server SG
Outputs:
  WebServerSG:
    Description: execlute the default security group
    Value: !GetAtt WebServerSG.GroupId
    Export: 
      Name: sg-webserver
  PubSubnetA:
    Description: Public subnet id
    Value: !Ref PubSubnetA
    Export: 
      Name: mypubsubnet-id
...

# aws cloudformation create-stack --template-body=file://network.yml --stack-name=network
# aws cloudformation update-stack --template-body=file://network.yml --stack-name=network