---
AWSTemplateFormatVersion: 2010-09-09
Description: > 
    This is the server cfn template
    This is a practical lab on Udacity's nanodegree program.
    Trying to acheive the challenge on my own.

Parameters: 
  EC2InstanceType: 
    Description: Type of the EC2 instance
    Type: String
    Default: t3.micro
  AMIID: 
    Type: String
    Default: ami-0b0ea68c435eb488d
    Description: AMI ID for the EC2 instance
  EC2KeyName: 
    Description: EC2 key name
    Type: String
    Default: EC2UsingCFNLab
  MyAZ: 
    Description: Availability zone
    Type: String
    Default: us-east-1a
Resources: 
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref MyAZ
      InstanceType: !Ref EC2InstanceType
      ImageId: !Ref AMIID
      NetworkInterfaces: 
        - AssociatePublicIpAddress: True
          DeviceIndex: 0
          SubnetId: !ImportValue mypubsubnet-id
          GroupSet:
            - !ImportValue sg-webserver
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
      Tags: 
        - Key: Name
          Value: !Ref EC2KeyName
        - Key: Project
          Value: UdacityND Lab

...

# aws cloudformation create-stack --template-body=file://server.yml --stack-name=server
# aws cloudformation update-stack --template-body=file://server.yml --stack-name=server